INFO = True
LastYear = 2100 # Last year of the computation 2100 or 2125
REG = 'Suriname' #'Netherlands', 'Bonaire', 'Saba', 'Suriname'
IBarE = False
TEMP = 'AR6'
GRE = 'IPCC'
ODYN = 'CMIP6'
ODSL_LIST = ['ACCESS-ESM1-5', 'CESM2-WACCM', 'CNRM-CM6-1', 'CNRM-ESM2-1', 
             'EC-Earth3', 'GISS-E2-1-G', 'INM-CM4-8', 'MIROC-ES2L', 
             'MPI-ESM1-2-LR', 'NESM3', 'NorESM2-LM', 'NorESM2-MM', 'UKESM1-0-LL']
ANT_DYN = 'VDL23_AS'
GIC = 'AR6'
LWS = 'AR6'
GAM = 1
COMB = 'IPCC'
SaveAllSamples = False
Corr = False
CorrGT = 0.6
CorrM = "Spearman"
CorrSMB = False
CorrDYN = False
NoU_O = False
NoU_G = False
NoU_A = False
NoU_Gl = False
Decomp = False
LowPass = 3
BiasCorr = False
InterpBack = True