INFO = True
LastYear = 2100 # Last year of the computation 2100 or 2125.
# Original box from Hylke: 51-60N, -3.5,7.5E
LOC = [60, 51, -3.5, 7.5] # lat_N, lat_S, lon_W, lon_E
LOC_FP = [53, 5] # lat, lon
IBarE = False
TEMP = 'AR5'
GRE = 'KNMI14'
ODYN = 'KNMI'
ANT_DYN = 'KNMI14'
GAM = 1
COMB = 'IPCC'
SaveAllSamples = False
Corr = False
CorrGT = 1
CorrM = "Spearman"
CorrSMB = False
CorrDYN = False
NoU_O = False
NoU_G = False
NoU_A = False
NoU_Gl = False
Decomp = False
LowPass = False